services:
  r2r-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: r2r-app
    environment:
      DATABASE_URL: 'postgresql+psycopg2://${R2R_POSTGRES_USER}:${R2R_POSTGRES_PASSWORD}@${R2R_POSTGRES_HOST}:${R2R_POSTGRES_PORT}/${R2R_POSTGRES_DBNAME}'
    depends_on:
      - r2r-db
    volumes:
      - '.:/app'
    healthcheck:
      test: curl --fail http://localhost:7272 || exit 1
  r2r-db:
    image: ankane/pgvector
    container_name: r2r-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - 'pg_data:/var/lib/postgresql/data'
    restart: unless-stopped
volumes:
  pg_data: null
