# Use an official Python 3.12 base image
FROM node:lts-alpine

# Install system dependencies including curl, git, and Node.js prerequisites
RUN apk add --no-cache \
    curl \
    git \
    build-base \
    postgresql-dev \
    ca-certificates

RUN git clone --single-branch https://github.com/SciPhi-AI/R2R-Application.git /workspaces/R2R-Frontend/R2R-Application
WORKDIR /workspaces/R2R-Frontend/R2R-Application
RUN git checkout 03b00fe1be0fc5dca58db22e02c2ba25baa77e89
# Ensure pnpm is updated and usable
RUN npm install -g pnpm
RUN pnpm update
ENV HOSTNAME=0.0.0.0
RUN pnpm install
RUN pnpm build

# Expose application ports
EXPOSE 3000

ENV PATH="/root/.local/bin:$PATH"
# Set default command to pnpm start
CMD ["pnpm", "start"]
