version: '3.8'
services:
  r2r-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: 'postgresql+psycopg2://postgres:password@r2r-db:5432/postgres'
    depends_on:
      - r2r-db
    volumes:
      - '.:/app'
  r2r-db:
    image: ankane/pgvector
    container_name: r2r-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - 'pg_data:/var/lib/postgresql/data'
      - './init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro'
    restart: unless-stopped
volumes:
  pg_data: null
